title: UK LLC Partner LPS Manual
author: UK LLC Data Team
logo: docs/images/UKLLC_Logo_Landscape_Black.jpg
email: support@ukllc.ac.uk
description: A manual for partner LPS data managers

execute:
  execute_notebooks: auto

repository:
  url: https://github.com/UKLLC/manual
  path_to_book: book
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  css_files:
    - custom.css
  extra_footer: |
    CC BY-NC-SA The UK LLC Manual and materials are available publicly under <a href="https://github.com/UKLLC/licencing">open source licenses</a>
  favicon: "docs/images/favicon.ico"  # A path to a favicon image

# control footer copywrite
sphinx:
  config                    : 
    html_show_copyright     : false